version: '3.7'
services:
  db:
    build: ./docker
    container_name: postgres
    env_file:
      - .env
    restart: always
    ports:
      - 5003:5432
    volumes:
      - ./.logs/data:/var/lib/postgresql/data
