version: '3.7'

services:
  db:
    build: ./docker
    env_file:
      - .env
    volumes:
      - ./.logs/migrate:/var/lib/mongodb
      - ./.logs/log:/var/log/mongodb
    ports:
      - 5002:27017
    restart: always
